### ISSUE TITLE
ImportError : PyFPE_jbuf, when trying importing h2o4gpu

### ISSUE THREAD

**Issue by mmmaks** [h2oai/h2o4gpu#304]
I am trying to install h2o4gpu by following this [link](https://github.com/h2oai/h2o4gpu/blob/master/README.md).
But when tried to import h2o4gpu in virtual environment, it is showing this importing error : 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/virtualenvironment/H2O/lib/python3.6/site-packages/h2o4gpu/__init__.py", line 11, in <module>
    from .solvers.pogs import Pogs
  File "/root/virtualenvironment/H2O/lib/python3.6/site-packages/h2o4gpu/solvers/__init__.py", line 8, in <module>
    from ..solvers.elastic_net import ElasticNetH2O
  File "/root/virtualenvironment/H2O/lib/python3.6/site-packages/h2o4gpu/solvers/elastic_net.py", line 13, in <module>
    from h2o4gpu.linear_model import coordinate_descent as sk
  File "/root/virtualenvironment/H2O/lib/python3.6/site-packages/h2o4gpu/linear_model/__init__.py", line 12, in <module>
    from .base import LinearRegressionSklearn
  File "/root/virtualenvironment/H2O/lib/python3.6/site-packages/h2o4gpu/linear_model/base.py", line 32, in <module>
    from ..utils.extmath import safe_sparse_dot
  File "/root/virtualenvironment/H2O/lib/python3.6/site-packages/h2o4gpu/utils/extmath.py", line 26, in <module>
    from .sparsefuncs_fast import csr_row_norms
ImportError: /root/virtualenvironment/H2O/lib/python3.6/site-packages/h2o4gpu/utils/sparsefuncs_fast.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf`

Found this [issue](https://github.com/h2oai/h2o4gpu/issues/201), which if I am right suggests to use bleeding edge version of h2o4gpu, but bleeding edge link on [this](https://github.com/h2oai/h2o4gpu/blob/master/README.md) page is broken.

**Comment by mdymczyk** [comment]
Hey @mmmaks yes the "stable" release might be having those kind of issues (we'll probably make a new release in a week or two).

As for the bleeding edge links - they should be working now so please try them out.

**Comment by mmmaks** [comment]
@mdymczyk , the bleeding edge links are still not working.
When trying to open this [link](https://s3.amazonaws.com/artifacts.h2o.ai/releases/bleeding-edge/ai/h2o/h2o4gpu/0.0.4/h2o4gpu-0.0.4-py36-none-any.whl), it is showing 
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>5B79FBB47B16379F</RequestId>
<HostId>
1vE4GqgpntMjq5vMyTq3lkxlq7lBGFikJFhL6CQezuEfjXtKuvSZTGsiiJZOdp/JLtw6F7FoZlU=
</HostId>
</Error>`

**Comment by mdymczyk** [comment]
@mmmaks the links changed, this is what you should be seeing now:

![screen shot 2017-11-22 at 16 00 12](https://user-images.githubusercontent.com/1208615/33114040-53b29ff8-cf9e-11e7-8002-7177d8df9d57.png)

We now provide 4 builds, for CUDA8/9 and with NCCL enabled and disabled. You can get the CUDA8/NCCL version [here](https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/bleeding-edge/ai/h2o/h2o4gpu/0.1-nccl-cuda8/h2o4gpu-0.1.0-py36-none-any.whl)

**Comment by mmmaks** [comment]
Thanks @mdymczyk , it's working now.
Can we use xgboost with gpu alongside h2o4gpu?? Because it was mentioned,

> NOTE: If you don't use a fresh environment, this will overwrite your py3nvml and xgboost installations to use our validated versions.

so i installed h2o4gpu in virtual environment.
Actually I want to create a notebook where we can import both xgboost with gpu and h2o4gpu.
Thanks.

**Comment by mdymczyk** [comment]
@mmmaks yes you can use xgboost like you'd do normally (here's an example https://github.com/h2oai/h2o4gpu/blob/master/examples/py/xgboost_simple_demo.ipynb).

What that note means is that we do bundle our own version of XGBoost inside H2O4GPU (github.com/h2oai/xgboost) because the approval/release process of the original wasn't fast enough for us. So any already installed version of XGBoost you had gets overwritten by it. You can always do `pip uninstall xgboost` and install a version you want.

Furthermore we also provide some wrapper classes around XGBoost which are ScikitLearn API compatible https://github.com/h2oai/h2o4gpu/blob/master/src/interface_py/h2o4gpu/solvers/xgboost.py

**Comment by mmmaks** [comment]
Thanks @mdymczyk 
But while using h2o4gpu to test the installation
`import h2o4gpu`
 `import numpy as np`
  `X = np.array([[1.,1.], [1.,4.], [1.,0.]])`
  `model = h2o4gpu.KMeans(n_clusters=2,random_state=1234).fit(X)`

I am getting this import error : 
`ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found`

While by running 
`strings /usr/lib64/libstdc++.so.6|grep GLIBCXX`
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

I am using centos-release-7-4.1708.el7.centos.x86_64
gcc version 4.8.5

**Comment by mdymczyk** [comment]
@mmmaks there were issues already regarding this problem - we currently don't support CentOS/RHEL as they have different g++/GLIBCXX requirements for CUDA than the machines we use for building our wheel (Ubuntu).

**Comment by pseudotensor** [comment]
@mmmaks Yes, and if you want to still try out h2o4gpu you can use the docker runtime image as explained in the README.md.  The docker is independent of the system.

**Comment by mmmaks** [comment]
Thanks @mdymczyk , @pseudotensor .
I will go with ubuntu image then.

**Comment by mmmaks** [comment]
@mdymczyk 
Is there any way we can configure h2o4gpu or centos, so that it can be used in centos? Apparently here we can not use ubuntu image for notebook for other issues.
Or, are you guys are working on giving support for centos?

**Comment by mdymczyk** [comment]
@mmmaks we will work on it but we have quite a few deadlines in the upcoming 2 weeks, so we cannot promise anything.

One workaround would be to build the project yourself by following the [build instructions](https://github.com/h2oai/h2o4gpu/blob/master/DEVEL.md).
